from .AddPersonalityTest import AddPersonalityTest
from .AddUrlTest import AddUrlTest
from .ChangeAppearanceTest import ChangeAppearanceTest
from .CreateBotTest import CreateBotTest
from .DeletePersonalityTest import DeletePersonalityTest
from .SignInTest import SignInTest
from .SignUpTest import SignUpTest
from .TrainFaqTest import TrainFaqTest
from .UpdatePersonalityTest import UpdatePersonalityTest
