from .CreateBotTests import CreateBotFeatureTests
from .KnowledgeTests import KnowledgeFeatureTests
from .LoginTests import LoginFeatureTests
from .RegisterTests import RegisterFeatureTests
from .IntegrationTest import IntegrationTest
from .ChangePasswordTests import ChangePasswordTests
from .AppearanceTests import AppearanceTests
from .FeedbackTests import FeedbackTests
from .ForgotPasswordTests import ForgotPasswordTests
